language: php

php:
  - 5.6

install:
  - composer install --prefer-dist --no-dev --optimize-autoloader --quiet

notifications:
  email:
    recipients:
      - shen.huang@104.com.tw
    on_success: always
    on_failure: always

script: phpunit -c phpunit.xml --coverage-text test/additionTest.php